#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amburer.Old_App_Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Amburer")]
	public partial class AccessLevelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertForgotPasswords(ForgotPasswords instance);
    partial void UpdateForgotPasswords(ForgotPasswords instance);
    partial void DeleteForgotPasswords(ForgotPasswords instance);
    partial void InsertUserGroups(UserGroups instance);
    partial void UpdateUserGroups(UserGroups instance);
    partial void DeleteUserGroups(UserGroups instance);
    partial void InsertGroupResources(GroupResources instance);
    partial void UpdateGroupResources(GroupResources instance);
    partial void DeleteGroupResources(GroupResources instance);
    partial void InsertAccessGroups(AccessGroups instance);
    partial void UpdateAccessGroups(AccessGroups instance);
    partial void DeleteAccessGroups(AccessGroups instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    partial void InsertResources(Resources instance);
    partial void UpdateResources(Resources instance);
    partial void DeleteResources(Resources instance);
    #endregion
		
		public AccessLevelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AmburerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AccessLevelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccessLevelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccessLevelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccessLevelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vResources> vResources
		{
			get
			{
				return this.GetTable<vResources>();
			}
		}
		
		public System.Data.Linq.Table<vGroupResources> vGroupResources
		{
			get
			{
				return this.GetTable<vGroupResources>();
			}
		}
		
		public System.Data.Linq.Table<vAccessGroups> vAccessGroups
		{
			get
			{
				return this.GetTable<vAccessGroups>();
			}
		}
		
		public System.Data.Linq.Table<vUserGroups> vUserGroups
		{
			get
			{
				return this.GetTable<vUserGroups>();
			}
		}
		
		public System.Data.Linq.Table<ForgotPasswords> ForgotPasswords
		{
			get
			{
				return this.GetTable<ForgotPasswords>();
			}
		}
		
		public System.Data.Linq.Table<vForgotPasswords> vForgotPasswords
		{
			get
			{
				return this.GetTable<vForgotPasswords>();
			}
		}
		
		public System.Data.Linq.Table<vValidForgotPasswords> vValidForgotPasswords
		{
			get
			{
				return this.GetTable<vValidForgotPasswords>();
			}
		}
		
		public System.Data.Linq.Table<UserGroups> UserGroups
		{
			get
			{
				return this.GetTable<UserGroups>();
			}
		}
		
		public System.Data.Linq.Table<GroupResources> GroupResources
		{
			get
			{
				return this.GetTable<GroupResources>();
			}
		}
		
		public System.Data.Linq.Table<AccessGroups> AccessGroups
		{
			get
			{
				return this.GetTable<AccessGroups>();
			}
		}
		
		public System.Data.Linq.Table<vUserAccess> vUserAccesses
		{
			get
			{
				return this.GetTable<vUserAccess>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
		
		public System.Data.Linq.Table<vUsers> vUsers
		{
			get
			{
				return this.GetTable<vUsers>();
			}
		}
		
		public System.Data.Linq.Table<Resources> Resources
		{
			get
			{
				return this.GetTable<Resources>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetMultipleAccess")]
		public ISingleResult<sp_GetMultipleAccessResult> sp_GetMultipleAccess([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> paramAccessTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> paramGroupCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> paramMasterCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paramAccessTypeCode, paramGroupCode, paramMasterCode);
			return ((ISingleResult<sp_GetMultipleAccessResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnGetUserBalance", IsComposable=true)]
		public System.Nullable<int> fnGetUserBalance([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserCode", DbType="Int")] System.Nullable<int> userCode)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userCode).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vResources")]
	public partial class vResources
	{
		
		private int _Code;
		
		private string _Name;
		
		private string _EngName;
		
		private string _BaseID;
		
		private System.Nullable<int> _MasterCode;
		
		public vResources()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngName", DbType="NVarChar(500)")]
		public string EngName
		{
			get
			{
				return this._EngName;
			}
			set
			{
				if ((this._EngName != value))
				{
					this._EngName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseID", DbType="VarChar(100)")]
		public string BaseID
		{
			get
			{
				return this._BaseID;
			}
			set
			{
				if ((this._BaseID != value))
				{
					this._BaseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCode", DbType="Int")]
		public System.Nullable<int> MasterCode
		{
			get
			{
				return this._MasterCode;
			}
			set
			{
				if ((this._MasterCode != value))
				{
					this._MasterCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vGroupResources")]
	public partial class vGroupResources
	{
		
		private int _Code;
		
		private System.Nullable<int> _GroupCode;
		
		private string _ResourceName;
		
		private System.Nullable<int> _ResourceCode;
		
		private System.Nullable<int> _AccessType;
		
		public vGroupResources()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this._GroupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceCode", DbType="Int")]
		public System.Nullable<int> ResourceCode
		{
			get
			{
				return this._ResourceCode;
			}
			set
			{
				if ((this._ResourceCode != value))
				{
					this._ResourceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessType", DbType="Int")]
		public System.Nullable<int> AccessType
		{
			get
			{
				return this._AccessType;
			}
			set
			{
				if ((this._AccessType != value))
				{
					this._AccessType = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAccessGroups")]
	public partial class vAccessGroups
	{
		
		private int _Code;
		
		private string _Name;
		
		private string _LevelName;
		
		public vAccessGroups()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelName", DbType="NVarChar(500)")]
		public string LevelName
		{
			get
			{
				return this._LevelName;
			}
			set
			{
				if ((this._LevelName != value))
				{
					this._LevelName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUserGroups")]
	public partial class vUserGroups
	{
		
		private int _Code;
		
		private System.Nullable<int> _UserCode;
		
		private System.Nullable<int> _GroupCode;
		
		private string _GroupName;
		
		private System.Nullable<int> _IGroupCode;
		
		public vUserGroups()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this._GroupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(200)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGroupCode", DbType="Int")]
		public System.Nullable<int> IGroupCode
		{
			get
			{
				return this._IGroupCode;
			}
			set
			{
				if ((this._IGroupCode != value))
				{
					this._IGroupCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ForgotPasswords")]
	public partial class ForgotPasswords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _UserCode;
		
		private string _Email;
		
		private string _GenKey;
		
		private System.Nullable<System.DateTime> _GenTime;
		
		private System.Nullable<bool> _Used;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnUserCodeChanging(System.Nullable<int> value);
    partial void OnUserCodeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnGenKeyChanging(string value);
    partial void OnGenKeyChanged();
    partial void OnGenTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnGenTimeChanged();
    partial void OnUsedChanging(System.Nullable<bool> value);
    partial void OnUsedChanged();
    #endregion
		
		public ForgotPasswords()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenKey", DbType="VarChar(50)")]
		public string GenKey
		{
			get
			{
				return this._GenKey;
			}
			set
			{
				if ((this._GenKey != value))
				{
					this.OnGenKeyChanging(value);
					this.SendPropertyChanging();
					this._GenKey = value;
					this.SendPropertyChanged("GenKey");
					this.OnGenKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GenTime
		{
			get
			{
				return this._GenTime;
			}
			set
			{
				if ((this._GenTime != value))
				{
					this.OnGenTimeChanging(value);
					this.SendPropertyChanging();
					this._GenTime = value;
					this.SendPropertyChanged("GenTime");
					this.OnGenTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Used", DbType="Bit")]
		public System.Nullable<bool> Used
		{
			get
			{
				return this._Used;
			}
			set
			{
				if ((this._Used != value))
				{
					this.OnUsedChanging(value);
					this.SendPropertyChanging();
					this._Used = value;
					this.SendPropertyChanged("Used");
					this.OnUsedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vForgotPasswords")]
	public partial class vForgotPasswords
	{
		
		private int _Code;
		
		private string _Email;
		
		private string _GenKey;
		
		private System.Nullable<System.DateTime> _GenTime;
		
		private System.Nullable<bool> _Used;
		
		private string _FirstName;
		
		private string _LastName;
		
		public vForgotPasswords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenKey", DbType="VarChar(50)")]
		public string GenKey
		{
			get
			{
				return this._GenKey;
			}
			set
			{
				if ((this._GenKey != value))
				{
					this._GenKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GenTime
		{
			get
			{
				return this._GenTime;
			}
			set
			{
				if ((this._GenTime != value))
				{
					this._GenTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Used", DbType="Bit")]
		public System.Nullable<bool> Used
		{
			get
			{
				return this._Used;
			}
			set
			{
				if ((this._Used != value))
				{
					this._Used = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(100)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(100)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vValidForgotPasswords")]
	public partial class vValidForgotPasswords
	{
		
		private int _Code;
		
		private System.Nullable<int> _UserCode;
		
		private string _GenKey;
		
		private System.Nullable<System.DateTime> _GenTime;
		
		private System.Nullable<bool> _Used;
		
		public vValidForgotPasswords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenKey", DbType="VarChar(50)")]
		public string GenKey
		{
			get
			{
				return this._GenKey;
			}
			set
			{
				if ((this._GenKey != value))
				{
					this._GenKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GenTime
		{
			get
			{
				return this._GenTime;
			}
			set
			{
				if ((this._GenTime != value))
				{
					this._GenTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Used", DbType="Bit")]
		public System.Nullable<bool> Used
		{
			get
			{
				return this._Used;
			}
			set
			{
				if ((this._Used != value))
				{
					this._Used = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserGroups")]
	public partial class UserGroups : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _UserCode;
		
		private int _GroupCode;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnUserCodeChanging(int value);
    partial void OnUserCodeChanged();
    partial void OnGroupCodeChanging(int value);
    partial void OnGroupCodeChanged();
    #endregion
		
		public UserGroups()
		{
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int NOT NULL")]
		public int GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this.OnGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._GroupCode = value;
					this.SendPropertyChanged("GroupCode");
					this.OnGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_UserGroups", Storage="_Users", ThisKey="UserCode", OtherKey="Code", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.UserGroups.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.UserGroups.Add(this);
						this._UserCode = value.Code;
					}
					else
					{
						this._UserCode = default(int);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GroupResources")]
	public partial class GroupResources : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _GroupCode;
		
		private System.Nullable<int> _ResourceCode;
		
		private System.Nullable<int> _AccessType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnGroupCodeChanging(System.Nullable<int> value);
    partial void OnGroupCodeChanged();
    partial void OnResourceCodeChanging(System.Nullable<int> value);
    partial void OnResourceCodeChanged();
    partial void OnAccessTypeChanging(System.Nullable<int> value);
    partial void OnAccessTypeChanged();
    #endregion
		
		public GroupResources()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this.OnGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._GroupCode = value;
					this.SendPropertyChanged("GroupCode");
					this.OnGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceCode", DbType="Int")]
		public System.Nullable<int> ResourceCode
		{
			get
			{
				return this._ResourceCode;
			}
			set
			{
				if ((this._ResourceCode != value))
				{
					this.OnResourceCodeChanging(value);
					this.SendPropertyChanging();
					this._ResourceCode = value;
					this.SendPropertyChanged("ResourceCode");
					this.OnResourceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessType", DbType="Int")]
		public System.Nullable<int> AccessType
		{
			get
			{
				return this._AccessType;
			}
			set
			{
				if ((this._AccessType != value))
				{
					this.OnAccessTypeChanging(value);
					this.SendPropertyChanging();
					this._AccessType = value;
					this.SendPropertyChanged("AccessType");
					this.OnAccessTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccessGroups")]
	public partial class AccessGroups : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public AccessGroups()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUserAccess")]
	public partial class vUserAccess
	{
		
		private int _UserCode;
		
		private string _Name;
		
		private System.Nullable<int> _AccessType;
		
		private string _ResName;
		
		private System.Nullable<int> _TypeCode;
		
		public vUserAccess()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessType", DbType="Int")]
		public System.Nullable<int> AccessType
		{
			get
			{
				return this._AccessType;
			}
			set
			{
				if ((this._AccessType != value))
				{
					this._AccessType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResName", DbType="VarChar(100)")]
		public string ResName
		{
			get
			{
				return this._ResName;
			}
			set
			{
				if ((this._ResName != value))
				{
					this._ResName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeCode", DbType="Int")]
		public System.Nullable<int> TypeCode
		{
			get
			{
				return this._TypeCode;
			}
			set
			{
				if ((this._TypeCode != value))
				{
					this._TypeCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _ID;
		
		private string _Name;
		
		private System.Nullable<int> _HCGenderCode;
		
		private string _Password;
		
		private System.Nullable<bool> _AutoLogin;
		
		private bool _Active;
		
		private string _Email;
		
		private EntitySet<UserGroups> _UserGroups;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnHCGenderCodeChanging(System.Nullable<int> value);
    partial void OnHCGenderCodeChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAutoLoginChanging(System.Nullable<bool> value);
    partial void OnAutoLoginChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Users()
		{
			this._UserGroups = new EntitySet<UserGroups>(new Action<UserGroups>(this.attach_UserGroups), new Action<UserGroups>(this.detach_UserGroups));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCGenderCode", DbType="Int")]
		public System.Nullable<int> HCGenderCode
		{
			get
			{
				return this._HCGenderCode;
			}
			set
			{
				if ((this._HCGenderCode != value))
				{
					this.OnHCGenderCodeChanging(value);
					this.SendPropertyChanging();
					this._HCGenderCode = value;
					this.SendPropertyChanged("HCGenderCode");
					this.OnHCGenderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoLogin", DbType="Bit")]
		public System.Nullable<bool> AutoLogin
		{
			get
			{
				return this._AutoLogin;
			}
			set
			{
				if ((this._AutoLogin != value))
				{
					this.OnAutoLoginChanging(value);
					this.SendPropertyChanging();
					this._AutoLogin = value;
					this.SendPropertyChanged("AutoLogin");
					this.OnAutoLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_UserGroups", Storage="_UserGroups", ThisKey="Code", OtherKey="UserCode")]
		public EntitySet<UserGroups> UserGroups
		{
			get
			{
				return this._UserGroups;
			}
			set
			{
				this._UserGroups.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserGroups(UserGroups entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_UserGroups(UserGroups entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUsers")]
	public partial class vUsers
	{
		
		private int _Code;
		
		private string _ID;
		
		private string _Name;
		
		private string _Email;
		
		private bool _Active;
		
		public vUsers()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resources")]
	public partial class Resources : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Name;
		
		private string _EngName;
		
		private System.Nullable<int> _TypeCode;
		
		private System.Nullable<int> _MasterCode;
		
		private string _EditPath;
		
		private string _BaseID;
		
		private System.Nullable<int> _BasicAccessType;
		
		private string _ResName;
		
		private System.Nullable<int> _Ordering;
		
		private EntitySet<Resources> _Resources1;
		
		private EntityRef<Resources> _Resource1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEngNameChanging(string value);
    partial void OnEngNameChanged();
    partial void OnTypeCodeChanging(System.Nullable<int> value);
    partial void OnTypeCodeChanged();
    partial void OnMasterCodeChanging(System.Nullable<int> value);
    partial void OnMasterCodeChanged();
    partial void OnEditPathChanging(string value);
    partial void OnEditPathChanged();
    partial void OnBaseIDChanging(string value);
    partial void OnBaseIDChanged();
    partial void OnBasicAccessTypeChanging(System.Nullable<int> value);
    partial void OnBasicAccessTypeChanged();
    partial void OnResNameChanging(string value);
    partial void OnResNameChanged();
    partial void OnOrderingChanging(System.Nullable<int> value);
    partial void OnOrderingChanged();
    #endregion
		
		public Resources()
		{
			this._Resources1 = new EntitySet<Resources>(new Action<Resources>(this.attach_Resources1), new Action<Resources>(this.detach_Resources1));
			this._Resource1 = default(EntityRef<Resources>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngName", DbType="NVarChar(500)")]
		public string EngName
		{
			get
			{
				return this._EngName;
			}
			set
			{
				if ((this._EngName != value))
				{
					this.OnEngNameChanging(value);
					this.SendPropertyChanging();
					this._EngName = value;
					this.SendPropertyChanged("EngName");
					this.OnEngNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeCode", DbType="Int")]
		public System.Nullable<int> TypeCode
		{
			get
			{
				return this._TypeCode;
			}
			set
			{
				if ((this._TypeCode != value))
				{
					this.OnTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._TypeCode = value;
					this.SendPropertyChanged("TypeCode");
					this.OnTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCode", DbType="Int")]
		public System.Nullable<int> MasterCode
		{
			get
			{
				return this._MasterCode;
			}
			set
			{
				if ((this._MasterCode != value))
				{
					if (this._Resource1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMasterCodeChanging(value);
					this.SendPropertyChanging();
					this._MasterCode = value;
					this.SendPropertyChanged("MasterCode");
					this.OnMasterCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditPath", DbType="VarChar(200)")]
		public string EditPath
		{
			get
			{
				return this._EditPath;
			}
			set
			{
				if ((this._EditPath != value))
				{
					this.OnEditPathChanging(value);
					this.SendPropertyChanging();
					this._EditPath = value;
					this.SendPropertyChanged("EditPath");
					this.OnEditPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseID", DbType="VarChar(100)")]
		public string BaseID
		{
			get
			{
				return this._BaseID;
			}
			set
			{
				if ((this._BaseID != value))
				{
					this.OnBaseIDChanging(value);
					this.SendPropertyChanging();
					this._BaseID = value;
					this.SendPropertyChanged("BaseID");
					this.OnBaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicAccessType", DbType="Int")]
		public System.Nullable<int> BasicAccessType
		{
			get
			{
				return this._BasicAccessType;
			}
			set
			{
				if ((this._BasicAccessType != value))
				{
					this.OnBasicAccessTypeChanging(value);
					this.SendPropertyChanging();
					this._BasicAccessType = value;
					this.SendPropertyChanged("BasicAccessType");
					this.OnBasicAccessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResName", DbType="VarChar(100)")]
		public string ResName
		{
			get
			{
				return this._ResName;
			}
			set
			{
				if ((this._ResName != value))
				{
					this.OnResNameChanging(value);
					this.SendPropertyChanging();
					this._ResName = value;
					this.SendPropertyChanged("ResName");
					this.OnResNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordering", DbType="Int")]
		public System.Nullable<int> Ordering
		{
			get
			{
				return this._Ordering;
			}
			set
			{
				if ((this._Ordering != value))
				{
					this.OnOrderingChanging(value);
					this.SendPropertyChanging();
					this._Ordering = value;
					this.SendPropertyChanged("Ordering");
					this.OnOrderingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Resource_Resource", Storage="_Resources1", ThisKey="Code", OtherKey="MasterCode")]
		public EntitySet<Resources> Resources1
		{
			get
			{
				return this._Resources1;
			}
			set
			{
				this._Resources1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Resource_Resource", Storage="_Resource1", ThisKey="MasterCode", OtherKey="Code", IsForeignKey=true)]
		public Resources Resource1
		{
			get
			{
				return this._Resource1.Entity;
			}
			set
			{
				Resources previousValue = this._Resource1.Entity;
				if (((previousValue != value) 
							|| (this._Resource1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Resource1.Entity = null;
						previousValue.Resources1.Remove(this);
					}
					this._Resource1.Entity = value;
					if ((value != null))
					{
						value.Resources1.Add(this);
						this._MasterCode = value.Code;
					}
					else
					{
						this._MasterCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("Resource1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Resources1(Resources entity)
		{
			this.SendPropertyChanging();
			entity.Resource1 = this;
		}
		
		private void detach_Resources1(Resources entity)
		{
			this.SendPropertyChanging();
			entity.Resource1 = null;
		}
	}
	
	public partial class sp_GetMultipleAccessResult
	{
		
		private System.Nullable<int> _GroupCode;
		
		private int _ResourceCode;
		
		public sp_GetMultipleAccessResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this._GroupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceCode", DbType="Int NOT NULL")]
		public int ResourceCode
		{
			get
			{
				return this._ResourceCode;
			}
			set
			{
				if ((this._ResourceCode != value))
				{
					this._ResourceCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
