#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amburer.Old_App_Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Amburer")]
	public partial class ProductsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSelectedProducts(SelectedProducts instance);
    partial void UpdateSelectedProducts(SelectedProducts instance);
    partial void DeleteSelectedProducts(SelectedProducts instance);
    partial void InsertProductCats(ProductCats instance);
    partial void UpdateProductCats(ProductCats instance);
    partial void DeleteProductCats(ProductCats instance);
    partial void InsertProductPictures(ProductPictures instance);
    partial void UpdateProductPictures(ProductPictures instance);
    partial void DeleteProductPictures(ProductPictures instance);
    partial void InsertProductComments(ProductComments instance);
    partial void UpdateProductComments(ProductComments instance);
    partial void DeleteProductComments(ProductComments instance);
    partial void InsertProductVisits(ProductVisits instance);
    partial void UpdateProductVisits(ProductVisits instance);
    partial void DeleteProductVisits(ProductVisits instance);
    partial void InsertProducts(Products instance);
    partial void UpdateProducts(Products instance);
    partial void DeleteProducts(Products instance);
    #endregion
		
		public ProductsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AmburerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vProductCats> vProductCats
		{
			get
			{
				return this.GetTable<vProductCats>();
			}
		}
		
		public System.Data.Linq.Table<SelectedProducts> SelectedProducts
		{
			get
			{
				return this.GetTable<SelectedProducts>();
			}
		}
		
		public System.Data.Linq.Table<vMostSoldProducts> vMostSoldProducts
		{
			get
			{
				return this.GetTable<vMostSoldProducts>();
			}
		}
		
		public System.Data.Linq.Table<ProductCats> ProductCats
		{
			get
			{
				return this.GetTable<ProductCats>();
			}
		}
		
		public System.Data.Linq.Table<vRandSelectAllProducts> vRandSelectAllProducts
		{
			get
			{
				return this.GetTable<vRandSelectAllProducts>();
			}
		}
		
		public System.Data.Linq.Table<vRandProducts> vRandProducts
		{
			get
			{
				return this.GetTable<vRandProducts>();
			}
		}
		
		public System.Data.Linq.Table<vProductPictures> vProductPictures
		{
			get
			{
				return this.GetTable<vProductPictures>();
			}
		}
		
		public System.Data.Linq.Table<vProductComments> vProductComments
		{
			get
			{
				return this.GetTable<vProductComments>();
			}
		}
		
		public System.Data.Linq.Table<ProductPictures> ProductPictures
		{
			get
			{
				return this.GetTable<ProductPictures>();
			}
		}
		
		public System.Data.Linq.Table<ProductComments> ProductComments
		{
			get
			{
				return this.GetTable<ProductComments>();
			}
		}
		
		public System.Data.Linq.Table<vSelectedProducts> vSelectedProducts
		{
			get
			{
				return this.GetTable<vSelectedProducts>();
			}
		}
		
		public System.Data.Linq.Table<ProductVisits> ProductVisits
		{
			get
			{
				return this.GetTable<ProductVisits>();
			}
		}
		
		public System.Data.Linq.Table<vProducts> vProducts
		{
			get
			{
				return this.GetTable<vProducts>();
			}
		}
		
		public System.Data.Linq.Table<Products> Products
		{
			get
			{
				return this.GetTable<Products>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vProductCats")]
	public partial class vProductCats
	{
		
		private int _Code;
		
		private string _Name;
		
		private System.Nullable<int> _MasterCode;
		
		public vProductCats()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCode", DbType="Int")]
		public System.Nullable<int> MasterCode
		{
			get
			{
				return this._MasterCode;
			}
			set
			{
				if ((this._MasterCode != value))
				{
					this._MasterCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SelectedProducts")]
	public partial class SelectedProducts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _ProductCode;
		
		private System.Nullable<int> _HCSelectTypeCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnProductCodeChanging(System.Nullable<int> value);
    partial void OnProductCodeChanged();
    partial void OnHCSelectTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCSelectTypeCodeChanged();
    #endregion
		
		public SelectedProducts()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSelectTypeCode", DbType="Int")]
		public System.Nullable<int> HCSelectTypeCode
		{
			get
			{
				return this._HCSelectTypeCode;
			}
			set
			{
				if ((this._HCSelectTypeCode != value))
				{
					this.OnHCSelectTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCSelectTypeCode = value;
					this.SendPropertyChanged("HCSelectTypeCode");
					this.OnHCSelectTypeCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vMostSoldProducts")]
	public partial class vMostSoldProducts
	{
		
		private System.Nullable<int> _ProductCode;
		
		private string _Title;
		
		private System.Nullable<int> _SellCount;
		
		public vMostSoldProducts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellCount", DbType="Int")]
		public System.Nullable<int> SellCount
		{
			get
			{
				return this._SellCount;
			}
			set
			{
				if ((this._SellCount != value))
				{
					this._SellCount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductCats")]
	public partial class ProductCats : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Name;
		
		private System.Nullable<int> _MasterCode;
		
		private System.Nullable<int> _ShowOrder;
		
		private EntitySet<ProductCats> _ProductCats1;
		
		private EntityRef<ProductCats> _ProductCat1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMasterCodeChanging(System.Nullable<int> value);
    partial void OnMasterCodeChanged();
    partial void OnShowOrderChanging(System.Nullable<int> value);
    partial void OnShowOrderChanged();
    #endregion
		
		public ProductCats()
		{
			this._ProductCats1 = new EntitySet<ProductCats>(new Action<ProductCats>(this.attach_ProductCats1), new Action<ProductCats>(this.detach_ProductCats1));
			this._ProductCat1 = default(EntityRef<ProductCats>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCode", DbType="Int")]
		public System.Nullable<int> MasterCode
		{
			get
			{
				return this._MasterCode;
			}
			set
			{
				if ((this._MasterCode != value))
				{
					if (this._ProductCat1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMasterCodeChanging(value);
					this.SendPropertyChanging();
					this._MasterCode = value;
					this.SendPropertyChanged("MasterCode");
					this.OnMasterCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowOrder", DbType="Int")]
		public System.Nullable<int> ShowOrder
		{
			get
			{
				return this._ShowOrder;
			}
			set
			{
				if ((this._ShowOrder != value))
				{
					this.OnShowOrderChanging(value);
					this.SendPropertyChanging();
					this._ShowOrder = value;
					this.SendPropertyChanged("ShowOrder");
					this.OnShowOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductCats_ProductCats", Storage="_ProductCats1", ThisKey="Code", OtherKey="MasterCode")]
		public EntitySet<ProductCats> ProductCats1
		{
			get
			{
				return this._ProductCats1;
			}
			set
			{
				this._ProductCats1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProductCats_ProductCats", Storage="_ProductCat1", ThisKey="MasterCode", OtherKey="Code", IsForeignKey=true)]
		public ProductCats ProductCat1
		{
			get
			{
				return this._ProductCat1.Entity;
			}
			set
			{
				ProductCats previousValue = this._ProductCat1.Entity;
				if (((previousValue != value) 
							|| (this._ProductCat1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProductCat1.Entity = null;
						previousValue.ProductCats1.Remove(this);
					}
					this._ProductCat1.Entity = value;
					if ((value != null))
					{
						value.ProductCats1.Add(this);
						this._MasterCode = value.Code;
					}
					else
					{
						this._MasterCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("ProductCat1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProductCats1(ProductCats entity)
		{
			this.SendPropertyChanging();
			entity.ProductCat1 = this;
		}
		
		private void detach_ProductCats1(ProductCats entity)
		{
			this.SendPropertyChanging();
			entity.ProductCat1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vRandSelectAllProducts")]
	public partial class vRandSelectAllProducts
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _SelectType;
		
		private string _PicFile;
		
		private System.Nullable<int> _Price;
		
		private System.Nullable<int> _HCSelectTypeCode;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _ShowOrder;
		
		private System.Nullable<int> _ProductCode;
		
		private string _SmallPicFile;
		
		private System.Nullable<int> _HCProductAvailabilitCode;
		
		private string _Description;
		
		public vRandSelectAllProducts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectType", DbType="NVarChar(500)")]
		public string SelectType
		{
			get
			{
				return this._SelectType;
			}
			set
			{
				if ((this._SelectType != value))
				{
					this._SelectType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile", DbType="NVarChar(200)")]
		public string PicFile
		{
			get
			{
				return this._PicFile;
			}
			set
			{
				if ((this._PicFile != value))
				{
					this._PicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSelectTypeCode", DbType="Int")]
		public System.Nullable<int> HCSelectTypeCode
		{
			get
			{
				return this._HCSelectTypeCode;
			}
			set
			{
				if ((this._HCSelectTypeCode != value))
				{
					this._HCSelectTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowOrder", DbType="Int")]
		public System.Nullable<int> ShowOrder
		{
			get
			{
				return this._ShowOrder;
			}
			set
			{
				if ((this._ShowOrder != value))
				{
					this._ShowOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCProductAvailabilitCode", DbType="Int")]
		public System.Nullable<int> HCProductAvailabilitCode
		{
			get
			{
				return this._HCProductAvailabilitCode;
			}
			set
			{
				if ((this._HCProductAvailabilitCode != value))
				{
					this._HCProductAvailabilitCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vRandProducts")]
	public partial class vRandProducts
	{
		
		private int _ProductCode;
		
		private string _Title;
		
		private string _SmallPicFile;
		
		private string _Description;
		
		private System.Nullable<int> _Price;
		
		private System.Nullable<int> _ProductCatCode;
		
		public vRandProducts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCatCode", DbType="Int")]
		public System.Nullable<int> ProductCatCode
		{
			get
			{
				return this._ProductCatCode;
			}
			set
			{
				if ((this._ProductCatCode != value))
				{
					this._ProductCatCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vProductPictures")]
	public partial class vProductPictures
	{
		
		private int _Code;
		
		private System.Nullable<int> _ProductCode;
		
		private string _PicFile;
		
		public vProductPictures()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile", DbType="NVarChar(200)")]
		public string PicFile
		{
			get
			{
				return this._PicFile;
			}
			set
			{
				if ((this._PicFile != value))
				{
					this._PicFile = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vProductComments")]
	public partial class vProductComments
	{
		
		private int _Code;
		
		private string _SenderName;
		
		private string _SenderEmail;
		
		private string _ProductTitle;
		
		private string _Status;
		
		private string _Comment;
		
		private System.Nullable<int> _UserCode;
		
		private string _CDate;
		
		private System.Nullable<int> _ProductCode;
		
		public vProductComments()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderName", DbType="NVarChar(50)")]
		public string SenderName
		{
			get
			{
				return this._SenderName;
			}
			set
			{
				if ((this._SenderName != value))
				{
					this._SenderName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderEmail", DbType="NVarChar(50)")]
		public string SenderEmail
		{
			get
			{
				return this._SenderEmail;
			}
			set
			{
				if ((this._SenderEmail != value))
				{
					this._SenderEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTitle", DbType="NVarChar(500)")]
		public string ProductTitle
		{
			get
			{
				return this._ProductTitle;
			}
			set
			{
				if ((this._ProductTitle != value))
				{
					this._ProductTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(500)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDate", DbType="VarChar(10)")]
		public string CDate
		{
			get
			{
				return this._CDate;
			}
			set
			{
				if ((this._CDate != value))
				{
					this._CDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductPictures")]
	public partial class ProductPictures : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _ProductCode;
		
		private string _PicFile;
		
		private string _SmallPicFile;
		
		private EntityRef<Products> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnProductCodeChanging(System.Nullable<int> value);
    partial void OnProductCodeChanged();
    partial void OnPicFileChanging(string value);
    partial void OnPicFileChanged();
    partial void OnSmallPicFileChanging(string value);
    partial void OnSmallPicFileChanged();
    #endregion
		
		public ProductPictures()
		{
			this._Products = default(EntityRef<Products>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					if (this._Products.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile", DbType="NVarChar(200)")]
		public string PicFile
		{
			get
			{
				return this._PicFile;
			}
			set
			{
				if ((this._PicFile != value))
				{
					this.OnPicFileChanging(value);
					this.SendPropertyChanging();
					this._PicFile = value;
					this.SendPropertyChanged("PicFile");
					this.OnPicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this.OnSmallPicFileChanging(value);
					this.SendPropertyChanging();
					this._SmallPicFile = value;
					this.SendPropertyChanged("SmallPicFile");
					this.OnSmallPicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_ProductPictures", Storage="_Products", ThisKey="ProductCode", OtherKey="Code", IsForeignKey=true)]
		public Products Products
		{
			get
			{
				return this._Products.Entity;
			}
			set
			{
				Products previousValue = this._Products.Entity;
				if (((previousValue != value) 
							|| (this._Products.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Products.Entity = null;
						previousValue.ProductPictures.Remove(this);
					}
					this._Products.Entity = value;
					if ((value != null))
					{
						value.ProductPictures.Add(this);
						this._ProductCode = value.Code;
					}
					else
					{
						this._ProductCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("Products");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductComments")]
	public partial class ProductComments : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _ProductCode;
		
		private System.Nullable<int> _UserCode;
		
		private string _Name;
		
		private string _Email;
		
		private string _Comment;
		
		private System.Nullable<System.DateTime> _CommentDate;
		
		private System.Nullable<int> _HCCommentStatusCode;
		
		private string _AdminComment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnProductCodeChanging(System.Nullable<int> value);
    partial void OnProductCodeChanged();
    partial void OnUserCodeChanging(System.Nullable<int> value);
    partial void OnUserCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCommentDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCommentDateChanged();
    partial void OnHCCommentStatusCodeChanging(System.Nullable<int> value);
    partial void OnHCCommentStatusCodeChanged();
    partial void OnAdminCommentChanging(string value);
    partial void OnAdminCommentChanged();
    #endregion
		
		public ProductComments()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CommentDate
		{
			get
			{
				return this._CommentDate;
			}
			set
			{
				if ((this._CommentDate != value))
				{
					this.OnCommentDateChanging(value);
					this.SendPropertyChanging();
					this._CommentDate = value;
					this.SendPropertyChanged("CommentDate");
					this.OnCommentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCCommentStatusCode", DbType="Int")]
		public System.Nullable<int> HCCommentStatusCode
		{
			get
			{
				return this._HCCommentStatusCode;
			}
			set
			{
				if ((this._HCCommentStatusCode != value))
				{
					this.OnHCCommentStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCCommentStatusCode = value;
					this.SendPropertyChanged("HCCommentStatusCode");
					this.OnHCCommentStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminComment", DbType="NVarChar(4000)")]
		public string AdminComment
		{
			get
			{
				return this._AdminComment;
			}
			set
			{
				if ((this._AdminComment != value))
				{
					this.OnAdminCommentChanging(value);
					this.SendPropertyChanging();
					this._AdminComment = value;
					this.SendPropertyChanged("AdminComment");
					this.OnAdminCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vSelectedProducts")]
	public partial class vSelectedProducts
	{
		
		private int _Code;
		
		private string _FaTitle;
		
		private string _SelectType;
		
		private string _LargePicFile;
		
		private System.Nullable<int> _Price;
		
		private System.Nullable<int> _HCSelectTypeCode;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _ShowOrder;
		
		private System.Nullable<int> _ProductCode;
		
		private string _SmallPicFile;
		
		private System.Nullable<int> _HCProductAvailabilityCode;
		
		private string _EnTitle;
		
		public vSelectedProducts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaTitle", DbType="NVarChar(500)")]
		public string FaTitle
		{
			get
			{
				return this._FaTitle;
			}
			set
			{
				if ((this._FaTitle != value))
				{
					this._FaTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelectType", DbType="NVarChar(500)")]
		public string SelectType
		{
			get
			{
				return this._SelectType;
			}
			set
			{
				if ((this._SelectType != value))
				{
					this._SelectType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargePicFile", DbType="NVarChar(200)")]
		public string LargePicFile
		{
			get
			{
				return this._LargePicFile;
			}
			set
			{
				if ((this._LargePicFile != value))
				{
					this._LargePicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSelectTypeCode", DbType="Int")]
		public System.Nullable<int> HCSelectTypeCode
		{
			get
			{
				return this._HCSelectTypeCode;
			}
			set
			{
				if ((this._HCSelectTypeCode != value))
				{
					this._HCSelectTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowOrder", DbType="Int")]
		public System.Nullable<int> ShowOrder
		{
			get
			{
				return this._ShowOrder;
			}
			set
			{
				if ((this._ShowOrder != value))
				{
					this._ShowOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCProductAvailabilityCode", DbType="Int")]
		public System.Nullable<int> HCProductAvailabilityCode
		{
			get
			{
				return this._HCProductAvailabilityCode;
			}
			set
			{
				if ((this._HCProductAvailabilityCode != value))
				{
					this._HCProductAvailabilityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnTitle", DbType="NVarChar(500)")]
		public string EnTitle
		{
			get
			{
				return this._EnTitle;
			}
			set
			{
				if ((this._EnTitle != value))
				{
					this._EnTitle = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductVisits")]
	public partial class ProductVisits : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _ProductCode;
		
		private System.DateTime _VisitDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnProductCodeChanging(int value);
    partial void OnProductCodeChanged();
    partial void OnVisitDateChanging(System.DateTime value);
    partial void OnVisitDateChanged();
    #endregion
		
		public ProductVisits()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int NOT NULL")]
		public int ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitDate", DbType="DateTime NOT NULL")]
		public System.DateTime VisitDate
		{
			get
			{
				return this._VisitDate;
			}
			set
			{
				if ((this._VisitDate != value))
				{
					this.OnVisitDateChanging(value);
					this.SendPropertyChanging();
					this._VisitDate = value;
					this.SendPropertyChanged("VisitDate");
					this.OnVisitDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vProducts")]
	public partial class vProducts
	{
		
		private int _Code;
		
		private string _Title;
		
		private string _Description;
		
		private string _CatalogFile;
		
		private string _TechnicalInfo;
		
		private string _SmallPicFile;
		
		private string _LargePicFile;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _HCProductAvailabilityCode;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<bool> _Special;
		
		private System.Nullable<int> _ViewNum;
		
		private System.Nullable<bool> _IsNew;
		
		private string _Availabality;
		
		public vProducts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatalogFile", DbType="NVarChar(200)")]
		public string CatalogFile
		{
			get
			{
				return this._CatalogFile;
			}
			set
			{
				if ((this._CatalogFile != value))
				{
					this._CatalogFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TechnicalInfo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TechnicalInfo
		{
			get
			{
				return this._TechnicalInfo;
			}
			set
			{
				if ((this._TechnicalInfo != value))
				{
					this._TechnicalInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this._SmallPicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargePicFile", DbType="NVarChar(200)")]
		public string LargePicFile
		{
			get
			{
				return this._LargePicFile;
			}
			set
			{
				if ((this._LargePicFile != value))
				{
					this._LargePicFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCProductAvailabilityCode", DbType="Int")]
		public System.Nullable<int> HCProductAvailabilityCode
		{
			get
			{
				return this._HCProductAvailabilityCode;
			}
			set
			{
				if ((this._HCProductAvailabilityCode != value))
				{
					this._HCProductAvailabilityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Special", DbType="Bit")]
		public System.Nullable<bool> Special
		{
			get
			{
				return this._Special;
			}
			set
			{
				if ((this._Special != value))
				{
					this._Special = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNum", DbType="Int")]
		public System.Nullable<int> ViewNum
		{
			get
			{
				return this._ViewNum;
			}
			set
			{
				if ((this._ViewNum != value))
				{
					this._ViewNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNew", DbType="Bit")]
		public System.Nullable<bool> IsNew
		{
			get
			{
				return this._IsNew;
			}
			set
			{
				if ((this._IsNew != value))
				{
					this._IsNew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Availabality", DbType="NVarChar(500)")]
		public string Availabality
		{
			get
			{
				return this._Availabality;
			}
			set
			{
				if ((this._Availabality != value))
				{
					this._Availabality = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Products : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Title;
		
		private string _Description;
		
		private string _CatalogFile;
		
		private string _TechnicalInfo;
		
		private string _SmallPicFile;
		
		private string _LargePicFile;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _HCProductAvailabilityCode;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<bool> _Special;
		
		private System.Nullable<bool> _IsNew;
		
		private System.Nullable<int> _ShowOrder;
		
		private EntitySet<ProductPictures> _ProductPictures;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCatalogFileChanging(string value);
    partial void OnCatalogFileChanged();
    partial void OnTechnicalInfoChanging(string value);
    partial void OnTechnicalInfoChanged();
    partial void OnSmallPicFileChanging(string value);
    partial void OnSmallPicFileChanged();
    partial void OnLargePicFileChanging(string value);
    partial void OnLargePicFileChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnHCProductAvailabilityCodeChanging(System.Nullable<int> value);
    partial void OnHCProductAvailabilityCodeChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnSpecialChanging(System.Nullable<bool> value);
    partial void OnSpecialChanged();
    partial void OnIsNewChanging(System.Nullable<bool> value);
    partial void OnIsNewChanged();
    partial void OnShowOrderChanging(System.Nullable<int> value);
    partial void OnShowOrderChanged();
    #endregion
		
		public Products()
		{
			this._ProductPictures = new EntitySet<ProductPictures>(new Action<ProductPictures>(this.attach_ProductPictures), new Action<ProductPictures>(this.detach_ProductPictures));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatalogFile", DbType="NVarChar(200)")]
		public string CatalogFile
		{
			get
			{
				return this._CatalogFile;
			}
			set
			{
				if ((this._CatalogFile != value))
				{
					this.OnCatalogFileChanging(value);
					this.SendPropertyChanging();
					this._CatalogFile = value;
					this.SendPropertyChanged("CatalogFile");
					this.OnCatalogFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TechnicalInfo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TechnicalInfo
		{
			get
			{
				return this._TechnicalInfo;
			}
			set
			{
				if ((this._TechnicalInfo != value))
				{
					this.OnTechnicalInfoChanging(value);
					this.SendPropertyChanging();
					this._TechnicalInfo = value;
					this.SendPropertyChanged("TechnicalInfo");
					this.OnTechnicalInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallPicFile", DbType="NVarChar(200)")]
		public string SmallPicFile
		{
			get
			{
				return this._SmallPicFile;
			}
			set
			{
				if ((this._SmallPicFile != value))
				{
					this.OnSmallPicFileChanging(value);
					this.SendPropertyChanging();
					this._SmallPicFile = value;
					this.SendPropertyChanged("SmallPicFile");
					this.OnSmallPicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LargePicFile", DbType="NVarChar(200)")]
		public string LargePicFile
		{
			get
			{
				return this._LargePicFile;
			}
			set
			{
				if ((this._LargePicFile != value))
				{
					this.OnLargePicFileChanging(value);
					this.SendPropertyChanging();
					this._LargePicFile = value;
					this.SendPropertyChanged("LargePicFile");
					this.OnLargePicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCProductAvailabilityCode", DbType="Int")]
		public System.Nullable<int> HCProductAvailabilityCode
		{
			get
			{
				return this._HCProductAvailabilityCode;
			}
			set
			{
				if ((this._HCProductAvailabilityCode != value))
				{
					this.OnHCProductAvailabilityCodeChanging(value);
					this.SendPropertyChanging();
					this._HCProductAvailabilityCode = value;
					this.SendPropertyChanged("HCProductAvailabilityCode");
					this.OnHCProductAvailabilityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Special", DbType="Bit")]
		public System.Nullable<bool> Special
		{
			get
			{
				return this._Special;
			}
			set
			{
				if ((this._Special != value))
				{
					this.OnSpecialChanging(value);
					this.SendPropertyChanging();
					this._Special = value;
					this.SendPropertyChanged("Special");
					this.OnSpecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNew", DbType="Bit")]
		public System.Nullable<bool> IsNew
		{
			get
			{
				return this._IsNew;
			}
			set
			{
				if ((this._IsNew != value))
				{
					this.OnIsNewChanging(value);
					this.SendPropertyChanging();
					this._IsNew = value;
					this.SendPropertyChanged("IsNew");
					this.OnIsNewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowOrder", DbType="Int")]
		public System.Nullable<int> ShowOrder
		{
			get
			{
				return this._ShowOrder;
			}
			set
			{
				if ((this._ShowOrder != value))
				{
					this.OnShowOrderChanging(value);
					this.SendPropertyChanging();
					this._ShowOrder = value;
					this.SendPropertyChanged("ShowOrder");
					this.OnShowOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Product_ProductPictures", Storage="_ProductPictures", ThisKey="Code", OtherKey="ProductCode")]
		public EntitySet<ProductPictures> ProductPictures
		{
			get
			{
				return this._ProductPictures;
			}
			set
			{
				this._ProductPictures.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProductPictures(ProductPictures entity)
		{
			this.SendPropertyChanging();
			entity.Products = this;
		}
		
		private void detach_ProductPictures(ProductPictures entity)
		{
			this.SendPropertyChanging();
			entity.Products = null;
		}
	}
}
#pragma warning restore 1591
